spring.application.name=authenticator-Backend
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/authentication
spring.datasource.username=root
spring.datasource.password=Nandhu07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true